### ISSUE TITLE
🧩插件发布 PQuery多功能查询插件免正则版

### ISSUE THREAD

**Issue by stardevel** [SereinDev/old-docs#6]
### 插件名称

PQuery多功能查询插件免正则版

### 插件描述

1.支持QQ群查询自己的账号在游戏里面的数据
2.免添加正则表达式
3.需要服务端安装PQuery.llse.js

### 插件功能

查询、排行榜等

### 署名相关信息

作者: Planet工作室-星辰开发组-苏苏
交流群: 639276103

### 插件下载链接（网盘/论坛/仓库）

https://www.minebbs.com/resources/serein-pquery.5804/

**Comment by Zaitonn** [comment]
https://market.serein.cc/resources/PQuery
